server:
    port: 8080

spring:
  main.show-banner: false
  application.name: sjjt
  thymeleaf:
    cache: false
    check-template-location: true
  messages:
    basename: i18n/messages
    cache-seconds: -1
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://127.0.0.1:3306/sjjt?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: sjjt2016
    password: SJJT_password@2016
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    openInView: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
    
multipart:
  max-file-size: 40Mb
  max-request-size: 120Mb


liquibase:
  change-log: classpath:config/liquibase/master.xml
  default-schema: sjjt

security:
  enable-csrf: false
  basic:
    enabled: false
  user:
    name: admin
    password: admin
  oauth2:
    client:
      client-id: mytestoauth2resource1
      client-secret: AB3456DCEF4590870076544334